### ISSUE TITLE
Allow sending existing users an opt-in email

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/learndash-mailchimp#60]
For sites which had users before installing this extension, it would be helpful to have some way to invite those people to subscribe. We can't just subscribe them without consent but we can send them an [opt-in email](https://kb.mailchimp.com/lists/growth/opt-in-methods-for-offline-subscribers) which will invite them to subscribe.

I am picturing a button on their user profile. Or really, we need to add a section to their user profile as touched on in #10. We should make that section and include in it an invite button which shows if the user is not subscribed already.

What I don't know how to do is get their segmentation data sent if they do follow through and opt-in. We probably can't include it in the email/link step so we might have to send the data when they come back...or have some cron which periodically syncs and/or a force sync feature.

Let's make that a separate issue and narrow this to only allowing an invite to be triggered.

**Comment by d4mation** [comment]
This shouldn't be necessary based on https://github.com/realbigplugins/learndash-mailchimp/issues/11#issuecomment-390189426

Auto-Subscribe is now implemented, so closing this.
