### ISSUE TITLE
Lists dropdown only returns up to 10 Lists

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/learndash-mailchimp#62]
We probably should use a Batch operation to pull down 10 at a time is my guess, considering they have Batches supported as an official thing in their API. If we set it to -1 or something and someone has 150 Lists it could turn out poorly.

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/#read-get_lists

**Comment by brashrebel** [comment]
Good catch.
